apiVersion: v1
kind: Service
metadata:
  name: basic-php-website-service
spec:
  selector:
    app: basic-php-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Specify the port you want to expose on the node
  type: NodePort  # Change the type to NodePort

